### ISSUE TITLE
pyBART transposes data

### ISSUE THREAD

**Issue by jtamir** [mrirecon/bart#168]
@Takishima 

The reading/writing of pyBART seems to transpose data. Here is an example where the phantom ends up being transposed:

```python
import pyBART as bart
im0 = bart.phantom('-x 128 im0.mem')
im1 = bart.load_cfl('im0.mem')
im2 = im1.copy()
bart.register_memory('im2.mem', im2)
print(bart.nrmse('im0.mem im2.mem')) # not zero
im3 = bart.load_cfl('im2.mem')
plt.figure()
plt.imshow(abs(im1.squeeze()))
plt.figure()
plt.imshow(abs(im3.squeeze()))
```
![image](https://user-images.githubusercontent.com/8716651/46970558-4f498b80-d06e-11e8-81e3-48c0cde0ff9a.png)
![image](https://user-images.githubusercontent.com/8716651/46970560-51abe580-d06e-11e8-84a7-73ddaa44058d.png)

**Comment by Takishima** [comment]
That is due to the fact that `im.copy()` by default produces arrays with C-ordering (row major) while BART uses F-ordering (column major). A way around it is to use `im.copy('A')`
I've modified the `register_memory` function to issue a warning in case it is called with a C-ordered array. In those cases a copy of the data will occur and `pyBART` should behave now as expected.

However, be aware that if a conversion does occur, then modifying the original data will not affect the data registered to BART (ie. the modifications will not be visible to BART).
