### ISSUE TITLE
Seek help

### ISSUE THREAD

**Issue by Sakatoku-Mai** [mrirecon/bart#327]
I found out in a python project that it uses bart (import bart) and when I use conda install bart I get an error and what should I do if I want this project to run.
![error](https://github.com/mrirecon/bart/assets/57064132/dad69550-0ebe-4894-8fd9-c8a99eb9bedb)

**Comment by hcmh** [comment]
Hey,

the issues on github are for problems / bugs in the Berkeley Advanced Reconstruction Toolbox, not for installation help.

Please use the mailing list at https://lists.eecs.berkeley.edu/sympa/info/mrirecon (mrirecon@lists.eecs.berkeley.edu) for that.

But also make sure that you are looking at the correct bart, since I do not think we published any Conda package, and version 0.0.3 also does not look like one of our versions.
